name: Publish ZenithProxy Docker Image to Github Packages

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/rfresh2/zenithproxy:latest
